export const REMOVER_PRODUTO_CARRINHO = "REMOVER_PRODUTO_CARRINHO";
export const ALTERAR_QUANTIDADE_PRODUTO_CARRINHO =
  "ALTERAR_QUANTIDADE_PRODUTO_CARRINHO";
export const ADICIONAR_OBSERVACAO_PRODUTO_CARRINHO =
  "ADICIONAR_OBSERVACAO_PRODUTO_CARRINHO";
export const SETAR_PRODUTOS_CARRINHO = "SETAR_PRODUTOS_CARRINHO";
